### ISSUE TITLE
feat: prepare scripts to check and demonstrate integration with RSK blockchain

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-evm-connector-examples#3]
- Go through the RSK blockchain docs: https://developers.rsk.co/ and try to understand how to get started with this blockchain
- Create a new `rsk` folder in the `scripts` folder
- Put few Node.js scripts (or one script) in the folder. The scripts (or script) should deploy a test contract (which uses RedStone oracles) on the RSK testnet and interact with this contract by calling at least one view function and at least one transaction which should rely on RedStone oracle data

**Comment by skromez** [comment]
Few things to mention
- It throws CALL_EXCEPTION error if we don't specify gas price (the same happens when we do a transaction on Metis blockchain)
- awaiting for transactions takes around 40-50 seconds which seems little bit long

but except for that everything else seems to work fine.
<img width="977" alt="image" src="https://user-images.githubusercontent.com/42495435/175114991-87cefaa9-8331-4feb-a9d4-99548d377cad.png">

**Comment by skromez** [comment]
@jakub-wojciechowski @hatskier 
I've run the script for the whole day/night (1000 contract deploys, transactions, and reading)
In these 1000 runs I got HH108: Cannot connect to the network rsk error 28 times during yesterday evening.

They were back-to-back connection errors, so it could be something with blockchain, my internet connection was fine

So in total downtime was 3.5% of the requests

https://pastebin.com/aG6yy5wC - logs

**Comment by alepc253** [comment]
@skromez are you using the public node or a local one run by you?

**Comment by skromez** [comment]
> @skromez are you using the public node or a local one run by you?

I'm using their public testnet node - https://public-node.testnet.rsk.co
